version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  registry:
    image: balance-registry:latest
    container_name: balanceron-registry
    ports:
      - "8081:8080"

  echo-unit-1:
    image: echo-unit:latest
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - INSTANCE_NAME=echo-unit-1
      - INSTANCE_WEIGHT=1

  echo-unit-2:
    image: echo-unit:latest
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - INSTANCE_NAME=echo-unit-2
      - INSTANCE_WEIGHT=10

  echo-unit-3:
    image: echo-unit:latest
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - INSTANCE_NAME=echo-unit-3
      - INSTANCE_WEIGHT=40

volumes:
  redis-data: