spring:
  application:
    name: echo-unit

server:
  port: ${SERVER_PORT:8081}

echounit:
  registry-url: http://host.docker.internal:8080/registry

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      access: unrestricted

logging:
  level:
    com.andrey.semeynikov.echounit: DEBUG