spring:
  application:
    name: balanceron
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

balanceron:
  loadbalancing:
    defaultAlgorithm: Round Robin

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      access: unrestricted
