global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'balancer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'echo_units'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['echo-unit-1:8083', 'echo-unit-2:8084', 'echo-unit-3:8085', 'echo-unit-4:8086']